### ISSUE TITLE
api.pwrtelegram.xyz redirects to docs.madelineproto.xyz

### ISSUE THREAD

**Issue by 4n70w4** [pwrtelegram/pwrtelegram#53]
I try `https://api.pwrtelegram.xyz/phonelogin?phone=+3984748839` but redorects to https://docs.madelineproto.xyz/

**Comment by danog** [comment]
That's intended, you should now use MadelineProto instead of PWRTelegram.If you want an HTTP API you can use https://github.com/xtrime-ru/TelegramApiServer.01.07.2019, 12:47, "4n70w4" <notifications@github.com>:I try https://api.pwrtelegram.xyz/phonelogin?phone=+3984748839 but redorects to https://docs.madelineproto.xyz/

**Comment by 4n70w4** [comment]
@danog thanks! May be need change https://github.com/pwrtelegram/pwrtelegram/blob/master/README.md

![image](https://user-images.githubusercontent.com/38257723/60441367-80c7ae80-9c1f-11e9-9b04-15461141dbb3.png)

**Comment by SmartManoj** [comment]
https://github.com/xtrime-ru/TelegramApiServer

**Comment by danog** [comment]
Yep, you should use TelegramApiServer now!
